### ISSUE TITLE
Docs are useless

### ISSUE THREAD

**Issue by mtliendo** [qccoders/qccoders.org#22]
Currently the docs provide no indication on how to do anything but run the app
Things the docs should do/contain:

- Explain resources on how to learn react (thinking in react article etc)
- Best practices for contributing
- Educate on the patent clause
- beginner and pro versions of docs

and so much more!

**Comment by model3volution** [comment]
card added in trello: https://trello.com/c/uU7qJuP2/28-backfill-tests-before-group-preview-release
